BuroBeautyApp/BuroBeauty.Website/Controllers/CalculationOfMastersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BuroBeauty.BLL;
using BuroBeauty.BLL.Implementation;
using BuroBeauty.DB.Entities;
using BuroBeauty.Repositories;
using BuroBeauty.Repositories.Implementation;
using Microsoft.Ajax.Utilities;
namespace BuroBeauty.Website.Controllers
{
    public class CalculationOfMastersController : Controller
    {
        private IOrderManager _orderManager;
        private IServiceManager _serviceManager;
        private IMasterManager _masterManager;
        private IMasterIncomeManager _masterIncomeManager;

        public CalculationOfMastersController(
            IOrderManager orderManager,
            IServiceManager serviceManager,
            IMasterManager masterManager,
            IMasterIncomeManager masterIncomeManager)
        {
            _orderManager = orderManager;
            _serviceManager = serviceManager;
            _masterManager = masterManager;
            _masterIncomeManager = masterIncomeManager;
        }

        // GET: CalculationOfMasters
        public ActionResult Index()
        {
            // Подсчет суммы на опр.дату
            var selectedDate = DateTime.Now;

            var items = _masterIncomeManager.GetAllMastersIncomeByDate(selectedDate);
            ViewBag.Total = items.Sum(x => x.TotalAmount);
            ViewBag.MastersTotal = items.Sum(x => x.AmountIncome);
            ViewBag.BuroTotal = ViewBag.Total - ViewBag.MastersTotal;
            ViewBag.SelectedDate = selectedDate;
            return View(items);
        }

        [HttpPost]
        public ActionResult Index(DateTime? date)
        {
            if (date == null)
            {
                return Index();
            }

            var items = _masterIncomeManager.GetAllMastersIncomeByDate(date);
            ViewBag.Total = items.Sum(x => x.TotalAmount);
            ViewBag.MastersTotal = items.Sum(x => x.AmountIncome);
            ViewBag.BuroTotal = ViewBag.Total - ViewBag.MastersTotal;
            
            ViewBag.SelectedDate = date;
            return View(items);
        }
    }
}

BuroBeautyApp/BuroBeauty.Website/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BuroBeauty.BLL;
using BuroBeauty.BLL.Implementation;
using BuroBeauty.DB.Entities;
using BuroBeauty.Repositories;
using BuroBeauty.Repositories.Implementation;
using Microsoft.Ajax.Utilities;
using NLog;

namespace MyTestProject.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private BuroBeauty.BLL.IOrderManager _orderManager;
        private IServiceManager _serviceManager;
        private IMasterManager _masterManager;

        public OrderController(
            IOrderManager orderManager,
            IServiceManager serviceManager,
            IMasterManager masterManager)
        {
            _orderManager = orderManager;
            _serviceManager= serviceManager;
            _masterManager = masterManager;
        }

        // GET: SoldServices
        public ActionResult Index()
        {
            Logger log = LogManager.GetCurrentClassLogger();
            log.Trace("trace message");
            log.Debug("debug message");
            log.Info("info message");
            log.Warn("warn message");
            log.Error("error message");
            log.Fatal("fatal message");
            // Подсчет суммы 
            var selectedDate = DateTime.Now;
            var items = _orderManager.GetOrdersByDate(selectedDate);
            ViewBag.Total = items.Sum(x => x.ServiceAmount);
            ViewBag.SelectedDate = selectedDate;

            try
            {
                throw new Exception("Bad ");
                log.Info("Everything works well");
            }
            catch (Exception ex)
            {
                log.Error(ex, "Something bad happened");
            }

            return View(items );
        }

        [HttpPost]
        public ActionResult Index(DateTime? date)
        {
          
            if (date == null)
            {
                return Index();
            }

            
            var items = _orderManager.GetOrdersByDate(date);
            ViewBag.Total = items.Sum(x => x.ServiceAmount);
            ViewBag.SelectedDate = date;
            return View(items);
        }
       
        // GET: SoldServices/Details/5
        public ActionResult Details(int id)
        {
            var order = _orderManager.GetOrderDetailsById(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: SoldServices/Create
        public ActionResult Create()
        {
            ViewBag.Services = _serviceManager.GetAllservices();
            ViewBag.Masters = _masterManager.GetAllMasters();
            
            return View(new Order()
            {
                PurchaseDate = DateTime.Now
            });
        }

        // POST: SoldServices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,MasterId,ServiceId,ServiceAmount,PurchaseDate")] Order order)
        {
            if (ModelState.IsValid)
            {
                
                _orderManager.CreateOrder(order);

                return RedirectToAction("Index");
            }

            ViewBag.Services = _serviceManager.GetAllservices();
            ViewBag.Masters = _masterManager.GetAllMasters();

            return View(order);
        }
        
        // GET: SoldServices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var order = _orderManager.GetOrderById(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.Services = _serviceManager.GetAllservices();
            ViewBag.Masters = _masterManager.GetAllMasters();

            return View(order);
        }

        // POST: SoldServices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,MasterId,ServiceId,ServiceAmount,PurchaseDate")] Order order)
        { 
            if (ModelState.IsValid)
            {
                _orderManager.UpdateOrder(order);

                return RedirectToAction("Index");
            }
            ViewBag.Services = _serviceManager.GetAllservices();
            ViewBag.Masters = _masterManager.GetAllMasters();

            return View(order);
        }  

       
        // GET: SoldServices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var order = _orderManager.GetOrderDetailsById(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: SoldServices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _orderManager.DeleteOrder(id);
            
            return RedirectToAction("Index");
        }

       
    }
}

BuroBeautyApp/BuroBeauty.Website/Views/Order/Create.cshtml
@using BuroBeauty.DB.Entities
@model BuroBeauty.DB.Entities.Order

@{
    ViewBag.Title = "";
}

<h2></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2" for="ServiceId">Услуга</label>

            @*@Html.LabelFor(model => model.ServiceName, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <select name="ServiceId" class="form-control">
                    @foreach (var service in (List<Service>)ViewBag.Services)
                    {
                        <option value="@service.Id">@service.Name</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MasterId">Мастер</label>
            @*@Html.LabelFor(model => model.ServiceName, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <select name="MasterId" class="form-control">
                    <option value="" @(Model.MasterId == null ? "selected='selected'" : "")>-</option>
                    @foreach (var master in (List<Master>)ViewBag.Masters)
                    {
                        <option value="@master.Id" @(Model.MasterId == master.Id ? "selected='selected'" : "")>@master.Name</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="PurchaseDate">Дата</label>
            <div class="col-md-10">
                @*<input class="form-control" id="PurchaseDate" name="PurchaseDate" value="@Model.PurchaseDate.ToString("yyyy-MM-dd")">*@
                <input type="text" class="form-control" autocomplete="false" id="datepicker" name="date" readonly="readonly" value="@Model.PurchaseDate.ToString("MM/dd/yyyy")" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ServiceAmount">Стоимость услуги</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ServiceAmount, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=" Добавить новую услугу" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться назад", "Index")
</div>

@section head_scripts{
    <script>
        $( function() {
            $( "#datepicker" ).datepicker();
        } );
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#datepicker").change(function () {
                $("#date_form").submit();
            })
        })
    </script>
}

BuroBeautyApp/BuroBeauty.Website/Views/Order/Delete.cshtml
@model BuroBeauty.DB.Entities.OrderDetails



@{
    ViewBag.Title = "";
}

<h2></h2>

<h3>Вы точно хотите удалить данную запись ?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
    <dt>
        Наименование услуги
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ServiceName)
    </dd>
         
    <dt>
        Фамилия Мастера
    </dt>
    <dd>
        @Html.DisplayFor(model => model.MasterFullName)
    </dd>

    <dt>
        Стоимость услуги
    </dt>
        <dd>
            @Html.DisplayFor(model => model.ServiceAmount)
        </dd>
        <dt>
            Дата
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

BuroBeautyApp/BuroBeauty.Website/Views/Order/Details.cshtml
@model BuroBeauty.DB.Entities.OrderDetails


@{
    ViewBag.Title = "Details";
}

<h2></h2>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
       
        <dt>
            Наименование услуги
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ServiceName)
        </dd>
        
        <dt>
            Фамилия Мастера
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MasterFullName)
        </dd>

        <dt>
           Стоимость услуги
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ServiceAmount)
        </dd>

        <dt>
            Дата
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Вернуться назад", "Index")
</p>

BuroBeautyApp/BuroBeauty.Website/Views/Order/Edit.cshtml
@model BuroBeauty.DB.Entities.Order
@using BuroBeauty.DB.Entities

@{
    ViewBag.Title = "Edit";
}

<h2></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2" for="ServiceId">Наименование услуги</label>
            <div class="col-md-10">
                <select name="ServiceId" class="form-control">
                    @foreach (var service in (List<Service>)ViewBag.Services)
                    {
                        <option value="@service.Id">@service.Name</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MasterId">Мастер</label>
            <div class="col-md-10">
                <select name="MasterId" class="form-control">
                    <option value="" @(Model.MasterId == null ? "selected='selected'" : "")>-</option>
                    @foreach (var master in (List<Master>)ViewBag.Masters)
                    {
                        <option value="@master.Id" @(Model.MasterId == master.Id ? "selected='selected'" : "")>@master.Name</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ServiceAmount">Стоимость услуги</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ServiceAmount, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="PurchaseDate">Дата</label>
            <div class="col-md-10">
                @*<input class="form-control" id="PurchaseDate" name="PurchaseDate" value="@Model.PurchaseDate.ToString("yyyy-MM-dd")">*@
                <input name="PurchaseDate" type="text" class="form-control" autocomplete="false" id="datepicker" readonly="readonly" value="@Model.PurchaseDate.ToString("MM/dd/yyyy")" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Изменить услугу" class="btn btn-default" />
            </div>
        </div>
    </div>

}
<div>
    @Html.ActionLink("Вернуться назад", "Index")
</div>

@section head_scripts{
    <script>
        $( function() {
            $( "#datepicker" ).datepicker();
        } );
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#datepicker").change(function () {
                $("#date_form").submit();
            })
        })
    </script>
}

BuroBeautyApp/BuroBeauty.Website/Views/Order/Index.cshtml
@model List<BuroBeauty.DB.Entities.OrderListItem>
@{
    ViewBag.Title = "Index";
}

<h5>Nail,Brow,Eyelashes</h5>

@using (Html.BeginForm("Index", "Order", FormMethod.Post, new
{
    @id = "date_form",
    autocomplete = "off"
}))
{
    <input type="text" autocomplete="false" id="datepicker" name="date" readonly="readonly" value="@ViewBag.SelectedDate.ToString("MM/dd/yyyy")" />
}

<p style="top:30%; left:73%" >
    @Html.ActionLink("Добавить услугу", "Create",null,new Dictionary<string, object>()
    {
        {"style" , "margin-right: 20px;"  }
    })

    @Html.ActionLink("Расчет Мастера", "Index", "CalculationOfMasters")
</p>


<table class="table">
    <style type="text/css">
        TABLE {
            width: 300px; /* Ширина таблицы */
            border: 1px solid black; /* Рамка вокруг таблицы */
            border-bottom: none; /* Убираем линию снизу */
        }

        TD, TH, TR {
            padding: 3px; /* Поля вокруг содержимого ячеек */
        }

        TH {
            text-align: left; /* Выравнивание по левому краю */
            background: white; /* Цвет фона */
            color: black; /* Цвет текста */
            border-bottom: 1px solid black; /* Линия снизу */
        }

        TD {
            border-bottom: 1px solid black; /* Линия снизу */
        }
    </style>

    <tr>
        <th>
            Наименование Услуги:
        </th>
        <th>
            Дата:
        </th>
        <th>
            Сумма:
        </th>
        <th>
            Мастер:
        </th>
        <th>
            Дополнительные функционал:
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceName)
            </td>
            <td>

                @{
                    string parameterValue = item.PurchaseDate.ToString("MM/dd/yyyy");
                }
                @Html.DisplayFor(modelItem => parameterValue)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceAmount)  р.
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MasterFullName)
            </td>
            <td>
                <u> @Html.ActionLink("Редактировать", "Edit", new { id = item.Id })</u>
                @*<u> @Html.ActionLink("Детали", "Details", new { id = item.Id })</u>*@
                <u> @Html.ActionLink("Удалить", "Delete", new { id = item.Id })</u>
            </td>
        </tr>
    }

    <tr>
        <td></td>
        <td><b>Итого</b></td>
        <td colspan="3"> @ViewBag.Total р. </td>
    </tr>
</table>

@section head_scripts{
    
    <script>
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#datepicker").change(function () {
                $("#date_form").submit();
            })
        })
    </script>
}